apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jupyter-ingress
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: proxy-public
          servicePort: 80
